version: '3.8'

services:
  lite-wiki:
    build:
      context: ./backend
    container_name: lite-wiki
    ports:
      - "3001:3000"  # 외부 포트:컨테이너 포트
    environment:
      JWT_SECRET_KEY: your_secret_key   # 반드시 강력한 비밀키로 변경
      DOCS_PATH: /data/docs
      UPLOADS_PATH: /data/uploads
      USER_DB_PATH: /data/config/users.json
      SETTINGS_PATH: /data/config/settings.json
      # GitHub OAuth 설정
      GITHUB_CLIENT_ID: Ov23lihUNKbcKywH2mXA
      GITHUB_CLIENT_SECRET: ff6ed1c60958509e0e5b41aa75f3dff4ac9d5dee
      GITHUB_ORG: your_organization_name
      GITHUB_CALLBACK_URL: http://localhost/auth/github/callback
    volumes:
      - ./data/docs:/data/docs
      - ./data/uploads:/data/uploads
      - ./data/config:/data/config
    restart: unless-stopped
  
volumes:
  litewiki-data:
    external: false