version: "3.8"

services:
  wiki:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lite-wiki
    ports:
      - "3001:3000"
    environment:
      BASE_URL: https://wiki.example.com/wiki  
      JWT_SECRET_KEY: your_strong_secret_key   
      DOCS_PATH: ./data/docs                  
      UPLOADS_PATH: ./data/uploads            
      USER_DB_PATH: ./data/users.json         
      SETTINGS_PATH: ./data/settings.json     
    volumes:
      - ./data/docs:${PWD}/data/docs
      - ./data/uploads:${PWD}/data/uploads
      - ./data/users.json:${PWD}/data/users.json
      - ./data/settings.json:${PWD}/data/settings.json
    restart: unless-stopped