version: '3.8'

services:
  lite-wiki:
    build:
      context: ./backend
    container_name: lite-wiki
    ports:
      - "3001:3000"  # 외부 포트:컨테이너 포트
    environment:
      JWT_SECRET_KEY: your_secret_key   # 반드시 강력한 비밀키로 변경
      DOCS_PATH: /data/docs
      UPLOADS_PATH: /data/uploads
      USER_DB_PATH: /data/config/users.json
      SETTINGS_PATH: /data/config/settings.json
      # GitHub OAuth 설정
      GITHUB_CLIENT_ID: github_client_id
      GITHUB_CLIENT_SECRET: github_client_secret
      GITHUB_ORG: github_org_name
      GITHUB_CALLBACK_URL: http://localhost:3001/auth/github/callback
    volumes:
      - ./data/docs:/data/docs
      - ./data/uploads:/data/uploads
      - ./data/config:/data/config
    restart: unless-stopped
    dns:
      - 8.8.8.8
  
volumes:
  litewiki-data:
    external: false